### ISSUE TITLE
Input Error: ERROR reading response from socket

### ISSUE THREAD

**Issue by crypdick** [kevinhughes27/mupen64plus-input-bot#4]
I am trying to run `mupen64plus` using the input bot, but it ends with a segfault after displaying `INI_FindSection trying to find name for UCODE` a minute or so. I also see a Mupen window, but the screen is black and unresponsive.

```
pepe@pepito ~/Apps/TensorKart-gym-record $ mupen64plus --input /usr/local/lib/mupen64plus/mupen64plus-input-bot.so /home/pepe/Apps/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
UI-Console:             Includes support for MIPS r4300 Debugger.
Core: Goodname: Mario Kart 64 (U) [!]
Core: Name: MARIOKART64         
Core: MD5: 3A67D9986F54EB282924FCA4CD5F6DFF
Core: CRC: 3E5055B6 2E92DA52
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1446
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus Bot Input Plugin' v0.0.1
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: opening /usr/share/games/mupen64plus/Glide64mk2.ini

INI_FindSection trying to find name for DEFAULT
Video: 3DNOW! detected.

Input: Mupen64Plus Bot Input Plugin version 0.0.1 initialized.
Core Status: Selected state slot: 1
INI_FindSection trying to find name for DEFAULT
INI_FindSection trying to find name for MARIOKART64
Video: Using TEXUMA extension.

&ConfigOpenSection is 0x7f6abf4bfd40
(II) Setting video mode 640x480...
Core: Setting video mode: 640x480
packed pixels extension used
NPOT extension used
use_fbo 1
Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f6ac9d3c6e0
INI_FindSection trying to find name for UCODE
Input Error: ERROR reading response from socket
Segmentation fault
```

**Comment by kevinhughes27** [comment]
are you using the latest version of both the input plugin and TensorKart? Also just confirming that it does work with the regular input plugin right?

**Comment by crypdick** [comment]
I had the latest input-bot, my TK was behind a few commits. I don't think that should make a difference for running `mupen64plus` though (I still haven't gotten as far as running `TensorKart/record.py`).

If I run with the default input it works (with or without the `--input` part):
`mupen64plus --input /usr/lib/x86_64-linux-gnu/mupen64plus/mupen64plus-input-sdl.so --plugindir /usr/lib/x86_64-linux-gnu/mupen64plus/ /home/pepe/Apps/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64`

Switching to input bot breaks it:
`$ mupen64plus --input /usr/lib/x86_64-linux-gnu/mupen64plus/mupen64plus-input-bot.so --plugindir /usr/lib/x86_64-linux-gnu/mupen64plus/ /home/pepe/Apps/gym-mupen64plus/gym_mupen64plus/ROMs/marioKart.n64`

Same with using the input-bot with `mupen64plus-qt`

**Comment by crypdick** [comment]
I don't know if this matters, but I had to change the default port since it seemed to already be in use. I edited the hard-coded port in `test/server.py` and in `src/controller.c`. I am running `server.py` when I execute `mupen64plus`.

**Comment by crypdick** [comment]
Ahh! I found out that the problem was that my `--input` directory was pointing to the wrong dir-- when I switched it to `/usr/local/lib/mupen64plus/mupen64plus-input-bot.so` the ROM loads! ^_^

**Comment by kevinhughes27** [comment]
what directory was it pointing too? I'm surprised it didn't crash with a clearer not found kind of error. Glad you got past this!

**Comment by crypdick** [comment]
Before I had changed the hard-coded port number in the source, I had copied that version into the plugins directory of `mupen64plus-qt` so that I could select the plug-in (I can figure out what the dir was if you need). Once I rebuilt and reinstalled I forgot to switch the --input dir in the non-Qt mupen64plus to the modified plugin at the default install path.

**Comment by kevinhughes27** [comment]
Ah makes sense!
