### ISSUE TITLE
Multi bot support

### ISSUE THREAD

**Issue by jaskarannagi19** [kevinhughes27/mupen64plus-input-bot#7]
I came across a post for multi mario kart support and Acymen stated he forked this repo and changed something to help him give multiple inputs but is repo is not open sourced can you help me in building that solution multi agent tensorkart?

**Comment by kevinhughes27** [comment]
Have you contacted this Acymen? I would start there and see if he will open source his changes. That would be your best bet and hopefully save everyone time.

**Comment by jaskarannagi19** [comment]
Tried connection no reply from him he has given gist of his changes and states that he states "As we are interested in a multi-agent environment, we needed a way to have multi input bots. Therefore based on mupen64plus-input-bot and on the official Input Plugin API, we created a 4 players input bots." and has given a controller.c file which is not much different than you and then he goes on to:"we had to update the gym-mupen64plus to support multi agent gym environnement. Therefore, we have forked the official repository and created our own gym-mupen64plus" which he doesnt expose and lastly he changed play.py file to include CurrentAgent coming somewhere from multi envir. I guess. I tried contacting him but he doesnt reply. :'(

**Comment by jaskarannagi19** [comment]
https://towardsdatascience.com/multi-agents-self-driving-mario-kart-with-tensorflow-and-cnns-c0f2812b4c50

this is the link. I wonder how you missed this link out

**Comment by jaskarannagi19** [comment]
https://github.com/aymen-mouelhi/gym-mupen64plus-1 
is this is the one I am looking for I dont see any commits from Aymen himself all commits comes from you abd his branch is very old.

**Comment by kevinhughes27** [comment]
The file in the post looks correct for the input plugin modified for multiple agents. They do describe exactly what they did to make it work with the gym, basically you'll have to modify the code that looks at the screen to only look at one half and then talk to one port of the input plugin and then the other half to the other port. Its unfortunate that they didn't open source their code but their approach is clear enough and should be follow-able. 

I'm not able to provide any more direction than that, you'll have to dig in and figure it out for yourself to finish your project. If you run into more specific issues or have questions please ask.

**Comment by jaskarannagi19** [comment]
Thanks for support Kevin I am a newbie in python and AI hope to find some
break

**Comment by jaskarannagi19** [comment]
@kevinhughes27 Hello again so lately I had to finally dig up this code here I want to ask you when I want to select multi player in the game than I believe the game should believe that I have 2 controllers now so there is something called controllerState class which is good only for one controller. Where Can I define this class again to initialize for second controller so that now I have 2 controller inside the program to do the selection of second player.....Thanks

**Comment by jaskarannagi19** [comment]
@kevinhughes27 Is there a place where I can see how many inputs (devices) are currently available all I need is problem is like I cannot use input device of first person to select player for second person so I need two input devices I modified input bot to have 2 devices but where to actually initialise them? and use them in navigation selection method

**Comment by kevinhughes27** [comment]
In the plugin file you define how many controllers there are then in the controller file you define where those controllers are read from. Right now the single controller is set to read from a hard coded port. You will need a new port for the second controller. 

Again I have to stress that I can't support broad questions about how to do this. I'm happy to help with specifics but I can't do this for you.

**Comment by jaskarannagi19** [comment]
@kevinhughes27 already did that. You are the only one who replies related to this project. I am still trying to understand different wings of the project there gym input out bot plugin anf gymmu64 env and your code. I have to update all three of these in order to run this.
Anyways thanks this is real move forward in the direction.

**Comment by kevinhughes27** [comment]
I'm not as familiar with the gym code to help off hand. You could try creating an issue over there, Brian usually responds to issues. As far as the input plugin is concerned I think this is closed.
